sudo: false
dist: trusty
language: generic
env:
  - PDK=release PDK_DISABLE_ANALYTICS=true
  - PDK=nightly PDK_DISABLE_ANALYTICS=true
before_install:
  - ".travis/install_pdk.sh"
script:
  - ".travis/test_script.sh"
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: RuLR/yl5FTfo7jDywF/7p6ba2zsP5SEB2jiPLQPwN7VFi8i3kJDsElHVMVQIVD1Ubuuo+LAdCKhugDpgeO/TRBjEfFDAV9IAKb1l61GR4YZv51AUMT4L6PDUeCStDbbuqI1goDIIeZmHo1o2rPmOMLuOkQLB1r84Lre3bNTb9CAQXIqFqQmlVG8FbkaUhArWKHaWE6MWol6WX5Sq3We1nXo12javfDEdATJGzbLSzuwLMt7/oCT40w2WeJBN2+VjFPuLr6lA6UCXuLKCcgUCHl6ibM658calCDP6I14C/NwGFjUMV13PbML6iHgpK2xLUtOEvDSVuBmrmCn/0WVbm332feEOucg+SmI2LF1c+kn/52lnQAwQ17+B0Nl0CXW4de5oR47rvhvhWDJ+9AYHkOokO9Misd7arCLTJ2Z0pvqAysDxVaVQPcIZAsTHeWQPDVe2SHOMVP5LX8nvD3GNQBv7447uO32cDo9QWalLLUFF77uAVNSRgwDSMhHN2NnPV02oCOti0XUIn3Bz2gaqAsoXK2VszwrVk6GR+9rqXmvn+wTg1RizIcq3HuuvXIeDaGt7HYvdYPSC/EWsI+1UKuBhGCN1aiVOgfxyGHSC2WfIefbV4HNDPCbBdZluKWlHFuvUfQzCip3cfj2uyMCpfqPfw0LzrgPELPHwymCGzHY=
